- name: check nslookup is exist
  shell: which nslookup
  failed_when: False
  register: result

- debug: var=result

- name: if not installed --> install nslookup
  yum:
    name: bind-utils
    state: present
  when: result.stdout_lines | length >= 1
